"""Add current_stock to products

Revision ID: 49541420ae2f
Revises: a1c951bc6c01
Create Date: 2025-12-26 20:41:26.960684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49541420ae2f'
down_revision = 'a1c951bc6c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stock', sa.Numeric(precision=15, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('current_stock')

    # ### end Alembic commands ###
