"""Add quotation workflow fields

Revision ID: 8d99eab4c902
Revises: 49541420ae2f
Create Date: 2025-12-26 20:46:36.867332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d99eab4c902'
down_revision = '49541420ae2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('converted_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###
