"""Rename PurchaseOrder fields for consistency

Revision ID: ceae38b7b5b4
Revises: 8d99eab4c902
Create Date: 2025-12-26 21:46:37.952979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceae38b7b5b4'
down_revision = '8d99eab4c902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('supplier_address_line1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('supplier_address_line2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('supplier_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_state_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('supplier_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_pincode', sa.String(length=10), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_po_number'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_po_date'))
        batch_op.create_index('idx_po_date', ['organization_id', 'order_date'], unique=False)
        batch_op.create_unique_constraint('uq_purchase_order_number', ['organization_id', 'order_number'])
        batch_op.drop_column('billing_state_code')
        batch_op.drop_column('billing_state')
        batch_op.drop_column('billing_country')
        batch_op.drop_column('billing_address_line1')
        batch_op.drop_column('po_number')
        batch_op.drop_column('billing_address_line2')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_pincode')
        batch_op.drop_column('po_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('billing_pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_address_line2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('po_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('billing_address_line1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_purchase_order_number', type_='unique')
        batch_op.drop_index('idx_po_date')
        batch_op.create_index(batch_op.f('idx_po_date'), ['organization_id', 'po_date'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_po_number'), ['organization_id', 'po_number'])
        batch_op.drop_column('supplier_pincode')
        batch_op.drop_column('supplier_country')
        batch_op.drop_column('supplier_state_code')
        batch_op.drop_column('supplier_state')
        batch_op.drop_column('supplier_city')
        batch_op.drop_column('supplier_address_line2')
        batch_op.drop_column('supplier_address_line1')
        batch_op.drop_column('order_date')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
