"""Add logo_data field to organizations

Revision ID: e61cc9e5990e
Revises: a2ea47098ed5
Create Date: 2026-01-06 20:59:23.840698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61cc9e5990e'
down_revision = 'a2ea47098ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.Text(), nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quotation_sales_order', 'sales_orders', ['sales_order_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotation_sales_order', type_='foreignkey')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('logo_data')

    # ### end Alembic commands ###
